force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{00000}</displayFormat>
        <label>Reg Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reg_Amount__c</fullName>
    <label>Reg Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Waitlist_Position__c.field-meta.xml
<CustomField>
    <fullName>Waitlist_Position__c</fullName>
    <label>Waitlist Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <displayFormat>VEN-{0000}</displayFormat>
        <label>Venue Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RegistrationEmailService.cls
public without sharing class RegistrationEmailService {
    
    /**
     * Send confirmation email when registration is successful (Confirmed)
     */
    public static void sendRegistrationConfirmedEmail(List<Registration__c> regs) {
        sendEmails(regs, 'confirmed');
    }
    
    /**
     * Send waitlisted email when event is full
     */
    public static void sendWaitlistedEmail(List<Registration__c> regs) {
        sendEmails(regs, 'waitlisted');
    }
    
    /**
     * Send cancellation email when user cancels
     */
    public static void sendCancellationEmail(List<Registration__c> regs) {
        sendEmails(regs, 'cancelled');
    }
    
    /**
     * Send promotion email when waitlisted person gets a spot
     */
    public static void sendPromotionEmails(List<Registration__c> regs) {
        sendEmails(regs, 'promoted');
    }
    
    private static void sendEmails(List<Registration__c> regs, String emailType) {
        if (regs == null || regs.isEmpty()) return;
        
        Set<Id> regIds = new Set<Id>();
        for (Registration__c r : regs) { regIds.add(r.Id); }
        
        List<Registration__c> fullRegs = [
            SELECT Id, Name, Reg_Amount__c, Waitlist_Position__c,
                   Event__r.Name, Event__r.Start_Date__c, Event__r.End_Date__c,
                   Event__r.Venue__r.City__c, Event__r.Venue__r.State__c,
                   Attendee__r.Name, Attendee__r.Email__c
            FROM Registration__c WHERE Id IN :regIds
        ];
        
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        
        for (Registration__c reg : fullRegs) {
            if (reg.Attendee__r.Email__c == null) continue;
            
            String subject;
            String body;
            String venue = (reg.Event__r.Venue__r != null) 
                ? reg.Event__r.Venue__r.City__c + ', ' + reg.Event__r.Venue__r.State__c 
                : 'TBD';
            String eventDates = 'Start: ' + String.valueOf(reg.Event__r.Start_Date__c) + 
                '\nEnd: ' + String.valueOf(reg.Event__r.End_Date__c);
            
            if (emailType == 'confirmed') {
                subject = 'Registration Confirmed - ' + reg.Event__r.Name;
                body = 'Dear ' + reg.Attendee__r.Name + ',\n\n' +
                    'Your registration for ' + reg.Event__r.Name + ' is confirmed!\n\n' +
                    'Registration #: ' + reg.Name + '\n' +
                    'Amount: $' + reg.Reg_Amount__c + '\n' +
                    'Venue: ' + venue + '\n' +
                    eventDates + '\n\n' +
                    'We look forward to seeing you there!\n\n' +
                    'Best regards,\nEpicEventz Team';
                    
            } else if (emailType == 'waitlisted') {
                subject = 'You\'re on the Waitlist - ' + reg.Event__r.Name;
                body = 'Dear ' + reg.Attendee__r.Name + ',\n\n' +
                    'Thank you for registering for ' + reg.Event__r.Name + '.\n\n' +
                    'The event is currently full. You have been placed on the waitlist.\n\n' +
                    'Registration #: ' + reg.Name + '\n' +
                    'Waitlist Position: #' + Integer.valueOf(reg.Waitlist_Position__c) + '\n\n' +
                    'We will notify you immediately if a spot opens up.\n\n' +
                    'Best regards,\nEpicEventz Team';
                    
            } else if (emailType == 'cancelled') {
                subject = 'Registration Cancelled - ' + reg.Event__r.Name;
                body = 'Dear ' + reg.Attendee__r.Name + ',\n\n' +
                    'Your registration for ' + reg.Event__r.Name + ' has been cancelled.\n\n' +
                    'Registration #: ' + reg.Name + '\n\n' +
                    'If this was a mistake, you can register again on our site.\n\n' +
                    'Best regards,\nEpicEventz Team';
                    
            } else if (emailType == 'promoted') {
                subject = 'You\'re In! Spot Available - ' + reg.Event__r.Name;
                body = 'Dear ' + reg.Attendee__r.Name + ',\n\n' +
                    'Great news! A spot has opened up and your registration for ' + 
                    reg.Event__r.Name + ' has been confirmed!\n\n' +
                    'Registration #: ' + reg.Name + '\n' +
                    'Venue: ' + venue + '\n' +
                    eventDates + '\n\n' +
                    'We look forward to seeing you there!\n\n' +
                    'Best regards,\nEpicEventz Team';
            }
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new List<String>{reg.Attendee__r.Email__c});
            mail.setSubject(subject);
            mail.setPlainTextBody(body);
            mail.setSenderDisplayName('EpicEventz');
            emails.add(mail);
        }
        
        if (!emails.isEmpty()) {
            Messaging.sendEmail(emails, false);
        }
    }
}